version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: libnpmpublish
    versions:
    - 4.0.0
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.1
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
